name: Feature request

description: Suggest a new feature or enhancement

title: "[FEATURE] "

labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a new feature! Please fill out the form below to provide us with details.**

  - type: input
    id: title
    attributes:
      label: Title
      description: A brief summary of the feature request
      placeholder: Feature request title

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature or enhancement
      placeholder: Describe the feature or enhancement

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Explain why this feature would be useful or beneficial. What problem does it solve?
      placeholder: Describe the motivation behind this feature request

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: |
        Provide examples of how this feature would be used. This helps in understanding the context and scope.
      placeholder: Describe the use cases for this feature

  - type: input
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Describe any alternative solutions or features you've considered
      placeholder: Describe alternatives you've considered

  - type: input
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: Additional context or screenshots



### Code of Conduct

- [ ] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project. (Required)
